deck/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.DeckListView.as_view(), name='deck_list'),
    path('deck/<int:pk>/', views.DeckDetailView.as_view(), name='deck_detail'),
    path('deck/new/', views.DeckNewView.as_view(), name="deck_new"),
    path('card_list/', views.CardListView.as_view(), name='card_list'),
    path('card/<int:pk>/', views.CardDetailView.as_view(), name='card_detail'),
    path('like/', views.LikeView, name='like'),

    path('deck_order_by/', views.DeckOrderByView, name='deck_order_by'),

    path('num_change/', views.NumChangeView, name='num_change'),

    path('num_reset/', views.NumReset, name='num_reset'),
    path('narrowing/', views.Narrowing, name='narrowing'),
    path('deck_narrowing/', views.deck_narrowing, name='deck_narrowing'),

    path('userpage/', views.MypageView.as_view(), name='mypage'),
    ]

deck/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.shortcuts import get_object_or_404

class Tag(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name
        
class Character(models.Model):
    rarity_choices = (
        ("1", 'B'), ("2", 'A'), ("3", 'S'), ("4", 'SS')
    )
    group_choices = (
        ('zyuken','287期受験生'),('ryodan','幻影旅団'),('mafian', 'マフィアンコミュニティー'),
        ('gi','G.Iプレイヤー'),('kimera','キメラアント'),('toubatu','蟻と闘う者'),('free','フリー')
    )
    subname = models.CharField(default=None, verbose_name='通り名', max_length=20)
    name = models.CharField(default=None, verbose_name='名前', max_length=20)
    attack = models.IntegerField(default=None, verbose_name='ATK')
    cost = models.IntegerField(default=None, verbose_name='コスト')
    rarity = models.CharField(default=None, verbose_name='レア度', max_length=5, choices=rarity_choices)
    group = models.CharField(default=None, verbose_name='GP', max_length=20, choices=group_choices)
    code = models.IntegerField(default=None, verbose_name='No.', primary_key=True)
    picture = models.ImageField(default=None, upload_to='images/')
    avility = models.TextField(default=None, verbose_name='能力')
    combo = models.TextField(default=None, verbose_name='コンボ')
    num = models.IntegerField(default=0, verbose_name="枚数", blank=True, null=True)

    def __str__(self):
        return self.name

class Action(models.Model):
    rarity_choices = (
        ("1", 'B'), ("2", 'A'), ("3", 'S'), ("4", 'SS')
    )
    group_choices = (
        ('zyuken','287期受験生'),('ryodan','幻影旅団'),('mafian', 'マフィアンコミュニティー'),
        ('gi','G.Iプレイヤー'),('kimera','キメラアント'),('toubatu','蟻と闘う者'),('free','フリー')
    )
    name = models.CharField(default=None, verbose_name='名前', max_length=20)
    cost = models.IntegerField(default=None, verbose_name='コスト')
    rarity = models.CharField(default=None, verbose_name='レア度', max_length=5, choices=rarity_choices)
    group = models.CharField(default=None, verbose_name='GP', max_length=20, choices=group_choices)
    code = models.IntegerField(default=None, verbose_name='No.', primary_key=True)
    picture = models.ImageField(default=None, upload_to='images/')
    avility = models.TextField(default=None, verbose_name='能力')
    num = models.IntegerField(default=0, verbose_name="枚数", blank=True, null=True)

    def __str__(self):
        return self.name

class Deck(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    group = models.CharField(default="", max_length=20, blank=True, null=True)
    title  = models.CharField(default="", max_length=50)
    description = models.TextField(blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    view_num  = models.IntegerField(default=0, verbose_name="閲覧数", blank=True, null=True)
    like_num = models.IntegerField(default=0, verbose_name="いいね数", blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class DeckOption(models.Model):
    deck = models.ForeignKey(Deck, on_delete=models.CASCADE)
    character = models.ForeignKey(Character, blank=True, null=True, on_delete=models.CASCADE)
    action = models.ForeignKey(Action, blank=True, null=True, on_delete=models.CASCADE)
    character_num = models.IntegerField(default=None, blank=True, null=True)
    action_num = models.IntegerField(default=None, blank=True, null=True)

class Like(models.Model):
    deck = models.ForeignKey(Deck, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

deck/templates/deck/base.html
{% load static %}
<html>
    <head>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-B3L6HYTS3Q"></script>
        <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-B3L6HYTS3Q');
        </script>
        <title>アリバトデッキ投稿サイト</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="{% static 'css/deck.css' %}">
        <link rel="stylesheet" href="{% static 'css/iziModal.min.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/1.4.1/css/ionicons.min.css">
        <script src="https://kit.fontawesome.com/d798c664a7.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>
        <script src="https://unpkg.com/vue-cookies@1.7.3/vue-cookies.js"></script>
    </head>
    
<body>
    <div class="container-fluid">
        <nav class="border navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#" style="color:rgb(98, 98, 98); font-weight: bold;">アリバト デッキ投稿サイト</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item"> <a class="nav-link" href="{% url 'card_list' %}">カードリスト</a> </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'account_logout' %}">ログアウト</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'account_login' %}">ログイン</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'account_signup' %}">ユーザー登録</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <div class="link_bar d-flex">
            {% block link_bar %}
            <div class="col-4 border p-1 align-items-center text-center bg-light">
                <a class="nav-link" href="{% url 'deck_new' %}">デッキ作成</a>
            </div>
            <div class="col-4 border p-1 align-items-center text-center bg-light">
                <a class="nav-link" href="{% url 'mypage' %}">マイページ</a>
            </div>
            <div class="col-4 border p-1 align-items-center text-center bg-light">
                <a class="nav-link" href="{% url 'deck_list' %}">投稿デッキ</a>
            </div>
            {% endblock %}
        </div>
        
        {% block content %}
        {% endblock %}

        <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src="{% static 'js/iziModal.min.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
        {% block js %}
        {% endblock %}
    </div>
</body>
</html>

deck/templates/deck/character_detail.html
{% extends 'deck/base.html' %}
{% load static %}

{% block content %}
    <div class="row"><p class="col">{{ character.card_subname }}</p></div>
    <div class="row"><p class="col">{{ character.card_name }}</p></div>
    <div class="row" id="card_detail_image"><img src="/media/{{card.picture}}"　width="250px" height="275px" class="d-block mx-auto"></div>
    <div class="row"><p class="col">{{ character.card_id }}</p></div>
    <div class="row"><p class="col">{{ character.rarity }}</p></div>
    <div class="row"><p class="col">{{ character.group }}</p></div>
    <div class="row"><p class="col">{{ character.cost }}</p></div>
    <div class="row"><p class="col">{{ character.attack }}</p></div>
    <div class="row"><p class="col">{{ character.avility_text }}</p></div>
    <div class="row"><p class="col">{{ character.combo_text }}</p></div>
{% endblock %}

deck/templates/deck/deck_detail.html
{% extends 'deck/base.html' %}

{% block content %}
    <input id="is_authenticated" type="hidden" value="{{ user.is_authenticated }}">
    <div class="deck-author">
        作成者：{{ deck.author}}
    </div>
    <div class="deck-created-date">
        作成日：{{ deck.created_date }}
    </div>
    <div>
        <div class="like-button d-inline" name="{{deck.id}}">
            {% if like_flag == 0 %}
                <img class="like d-inline" src="/media/images/like_before.webp" style="width: 5vw;">
            {% else %}
                <img class="like d-inline" src="/media/images/like_after.webp" style="width: 5vw;">
            {% endif %}
        </div>
        <p id="like_num" class="d-inline" name="like_num">{{ like_num }}</p>
        <div id="login_massage" class="d-inline" style="color: red;">
        </div>
    </div>


    <!-- デッキテーブル -->
    <div id="deck_image_table" class="row border border-dark rounded mb-1 justify-content-center">
            <label class="d-inline-block" sytle="margin: 0px;">
                <!-- アクション -->
                {% for action in action_list %}
                    <img src="/media/{{action.action.picture}}" style="width: 14vw;">
                    {% if action.action_num == 2 %}
                        <img src="/media/{{action.action.picture}}" style="width: 14vw;">
                    {% endif %}
                {% endfor %}
                <!-- キャラ -->
                {% for card in card_list %}
                    <img src="/media/{{card.character.picture}}" style="width: 14vw;">
                    {% if card.character_num == 2 %}
                        <img src="/media/{{card.character.picture}}" style="width: 14vw;">
                    {% endif %}
                {% endfor %}
            </label>
        </div>
    </div>
{% endblock %}

{% block js %}
<script>
    $(document).ready(function(event){
        $(document).on('click', '.like-button', function(event){
            event.preventDefault();
            $.ajax({
                method: 'POST',
                url: "{% url 'like' %}",
                data: {
                    'deck_id': $(this).attr('name'),
                    'csrfmiddlewaretoken': '{{ csrf_token }}'},
                dataType: 'json',
                success: function(response){
                    if(response.is_authenticated == true){
                        selector = document.getElementsByName(response.deck_id);
                        if(response.liked){
                            console.log("いいねしました");
                            $(selector).html("<img class='like d-inline' src='/media/images/like_after.webp' style='width: 5vw;'>");
                        }
                        else {
                            console.log("いいねを解除しました。");
                            $(selector).html("<img class='like d-inline' src='/media/images/like_before.webp' style='width: 5vw;'>");
                        }
                        selector2 = document.getElementsByName('like_num');
                        $(selector2).text(response.count);
                    }
                    else if(response.is_authenticated == false){
                        console.log("ログインしてください");
                        selector = document.getElementById('login_massage');
                        $(selector).text(" *いいねするにはログインが必要です");
                    }
                },
                fail: function(){
                    console.log("失敗しました。")
                }
            });
        });
    });
</script>
{% endblock %}

deck/templates/deck/deck_list.html
{% extends 'deck/base.html' %}

{% block link_bar %}
<div class="col-4 border p-1 align-items-center text-center">
    <a class="nav-link" href="{% url 'deck_new' %}">デッキ作成</a>
</div>
<div class="col-4 border p-1 align-items-center text-center">
    <a class="nav-link" href="{% url 'mypage' %}">マイページ</a>
</div>
<div class="current col-4 border p-1 align-items-center text-center">
    <a class="nav-link" href="{% url 'deck_list' %}">投稿デッキ</a>
</div>
{% endblock %}

{% block content %}
{{ order_by.created_date|json_script:"order_by_created_date" }}
{{ order_by.like_num|json_script:"order_by_like_num" }}
<div id="app">
    <!-- <div id="mypage_header" class="col-12 mt-3 pl-1">
        <div class="text col-12 p-0 text-left">
            <a href="{% url 'deck_list' %}">ホーム</a>
            ＞
        </div>
    </div> -->
    <!-- タイムライン・ランキング -->
    <div id="" class="row col-12 my-2">
        <div class="col-12 my-1 p-0">
            <div class='btn-toolbar justify-content-center' role="toolbar">
                <div id="deck_list_button" class="col-12 btn-group" role="group">
                    <button type="button" id="order_by_created_date_button" class="current col-6 btn btn-gray border" name="order_by" value="created_date" v-on:click="OrderByCreatedDate">
                        投稿日
                    </button>
                    <button type="button" id="order_by_like_num_button" class="col-6 btn btn-gray border text-center" name="order_by" value="like_num" v-on:click="OrderByLike">
                        いいね数
                    </button>
                </div>
            </div>
        </div>
    </div>
    <!-- 作成日順 -->
    <div id="order_by_created_date" v-for="deck in decks.order_by.created_date.info" :key="`first-${deck.id}`" v-show="decks.order_by.created_date.show">
        <div class="row mt-1 border pt-3">
            <div class="d-flex flex-row col-12">
                <!-- デッキグループ画像 -->
                <div class="align-self-center">
                    <img :src="deck.group" style="width: 15vw;">
                </div>
                <!-- デッキ情報 -->
                <div class="deck text-left col-10">
                    <!-- 作者・作成日 -->
                    <p class="author-date m-0" style="color: gray; font-size: 2vw;">
                        [[ deck.author ]] : [[ deck.created_date ]]
                    </p>
                    <div class="deck-header mt-1">
                        <!-- タイトル -->
                        <p class="title">
                            <a :href="deck.detail_url" sytle="font-weight: bold; color: rgb(37, 37, 37) !important;">
                                [[ deck.title ]]
                            </a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="like col-12 d-flex flex-row justify-content-end">
                <div class="like-image d-inline-block">
                    <!-- いいね画像 -->
                    <img class="" src="/media/images/like_after.webp" style="width: 3vw;">
                </div>
                <!-- いいね数 -->
                <div class="like-num d-inline-block">
                    [[ deck.like_num ]]
                </div>
            </div>
        </div>
    </div>

    <!-- いいね順 -->
    <div id="order_by_like_num" v-for="deck in decks.order_by.like_num.info" :key="`second-${deck.id}`" v-show="decks.order_by.like_num.show">
        <div class="row mt-1 border pt-3">
            <div class="d-flex flex-row col-12">
                <!-- デッキグループ画像 -->
                <div class="align-self-center">
                    <img :src="deck.group" style="width: 15vw;">
                </div>
                <!-- デッキ情報 -->
                <div class="deck text-left col-10">
                    <!-- 作者・作成日 -->
                    <p class="author-date m-0" style="color: gray; font-size: 2vw;">
                        [[ deck.author ]] : [[ deck.created_date ]]
                    </p>
                    <div class="deck-header mt-1">
                        <!-- タイトル -->
                        <p class="title">
                            <a :href="deck.detail_url" sytle="font-weight: bold; color: rgb(37, 37, 37) !important;">
                                [[ deck.title ]]
                            </a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="like col-12 d-flex flex-row justify-content-end">
                <div class="like-image d-inline-block">
                    <!-- いいね画像 -->
                    <img class="" src="/media/images/like_after.webp" style="width: 3vw;">
                </div>
                <!-- いいね数 -->
                <div class="like-num d-inline-block">
                    [[ deck.like_num ]]
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/locale/ja.js" type="text/javascript"></script>
<script>
    var app = new Vue({
        el: '#app',
        delimiters: ['[[',']]'],
        data: {
            deck_info: {},
            decks: {
                order_by: {
                    created_date: {
                        info: JSON.parse(document.getElementById('order_by_created_date').textContent),
                        show: true,
                    },
                    like_num: {
                        info: JSON.parse(document.getElementById('order_by_like_num').textContent),
                        show: false,
                    },
                },
            },
        },
        methods: {
            TimeChange: function(decks) {
                for (key in decks) {
                    decks[key].created_date = moment(decks[key].created_date).format('LLL');
                }
                return decks
            },
            OrderByCreatedDate: function() {
                this.decks.order_by.created_date.show = true;
                this.decks.order_by.like_num.show = false;
                $('#order_by_like_num_button').removeClass('current');
                $('#order_by_created_date_button').addClass('current');
            },
            OrderByLike: function() {
                this.decks.order_by.created_date.show = false;
                this.decks.order_by.like_num.show = true;
                $('#order_by_created_date_button').removeClass('current');
                $('#order_by_like_num_button').addClass('current');
                // event.preventDefault();
                // $.ajax({
                //     method: 'POST',
                //     url: "{% url 'deck_order_by' %}",
                //     data: {
                //         'order_by': $('#order_by_like_num_button').attr('value'),
                //         'csrfmiddlewaretoken': '{{ csrf_token }}'},
                //     dataType: 'json',
                //     success: function(response){
                //         app.decks.order_by.like_num.info = app.TimeChange(response.decks)
                //         app.decks.order_by.created_date.show = false;
                //         app.decks.order_by.like_num.show = true;
                //     }
                // });
            }
        },
        mounted: function() {
            this.decks.order_by.created_date.info = this.TimeChange(this.decks.order_by.created_date.info);
            this.decks.order_by.like_num.info = this.TimeChange(this.decks.order_by.like_num.info);
            console.log(this.decks.order_by.like_num.info);
        }
    })
</script>
{% endblock %}

deck/templates/deck/index.html
{% extends 'deck/base.html' %}
{% load static %}

{% block content %}
{{ image_url_list|json_script:"image_url_list" }}
{{ id_url_list|json_script:"id_url_list" }}

<!-- 検索フォーム -->
<form id="serch-form" method="POST">
    {% csrf_token %}
    <div class="rarity">
        【レアリティ】<br>
        <label><input type="checkbox" name="rarity" value="SS">SS</label>
        <label><input type="checkbox" name="rarity" value="S">S</label>
        <label><input type="checkbox" name="rarity" value="A">A</label>
        <label><input type="checkbox" name="rarity" value="B">B</label><br>
    </div>
    
    <div class="group">
        【グループ】<br>
        <label id="zyuken"><input type="checkbox" name="group" value="zyuken">287期受験生</label>
        <label id="ryodan"><input type="checkbox" name="group" value="ryodan">幻影旅団　</label>
        <label id="mafian"><input type="checkbox" name="group" value="mafian">マフィアン</label>
        <label id="gi"><input type="checkbox" name="group" value="gi">G.I</label><br>
        <label id="kimera"><input type="checkbox" name="group" value="kimera">キメラアント</label>
        <label id="toubatu"><input type="checkbox" name="group" value="toubatu">蟻と闘う者</label>
        <label id="free"><input type="checkbox" name="group" value="free">フリー</label><br>
    </div>
    <input type="submit" id="serch" value="絞り込み">
</form>

<!-- ページナンバー -->
<!-- <span id="prev">前のページ</span> ＜ <span id="page"></span> ＞ <span id="next">次のページ</span> -->
<!-- カードリストテーブル -->
<div id="card_list_table"></div>
{% include "deck/pagination.html" %}
{% endblock %}

{% block js %}
<script src="{% static 'js/card_list_table.js' %}"></script>
{% endblock %}

deck/templates/deck/pagination.html
{% if is_paginated %}
<nav aria-label="Page navigation" id="paginate" class="col-12">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link bg-white text-dark" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    {% endif %}
    {% for num in paginator.page_range %}
    {% if page_obj.number == num %}
    <li class="page-item active">
      <span class="page-link bg-white text-dark">
        {{ num }}
        <span class="sr-only ">(current)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link bg-white text-dark" href="?page={{ num }}">{{ num }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link bg-white text-dark" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}